### ISSUE TITLE
Feature: Support importing of notes

### ISSUE THREAD

**Issue by kabili207** [neobooru/SzuruChrome#27]
It would be very helpful to import [notes](https://github.com/rr-/szurubooru/blob/master/doc/API.md#note) when they are available. This would obviously depend on neobooru/neo-scraper#10.

**Comment by neobooru** [comment]
I added a very basic implementation of this feature. It currently only supports Danbooru and Gelbooru. It also doesn't actually show the notes in the preview window, so that is something to be added in a future version. Could you test if it correctly imports notes on your posts?

Also, some sites allow notes to have <big> text, this is not supported. Italics and stuff should work, mostly, I think.

**Comment by kabili207** [comment]
Both sites seem to work for me without issue
